### ISSUE TITLE
Missing Symbols with LaTeX Strings

### ISSUE THREAD

**Issue by gdmsl** [JuliaGraphics/Luxor.jl#198]
Hi all

I am getting started with Luxor to draw quick schemes in Pluto notebooks. 

While drawing graphics with LaTeX strings inside, I encountered a problem where some symbols (such as `\rangle` in this example) get substituted by a missing symbol mark (square with question mark).

Thanks for the amazing library!

This is the code used to generate the image attached:

```
using Luxor
using MathTeXEngine # had to be installed separately because of https://github.com/JuliaGraphics/Luxor.jl/issues/195
Luxor.@draw begin
	a1, b1 = Luxor.Point(-150, 150), Luxor.Point(-50, 150)
	a2, b2 = Luxor.Point(-50, -150), Luxor.Point(50, -150)
	a3, b3 = Luxor.Point(50, 100), Luxor.Point(150, 100)

	c1 = (a1 + b1) / 2
	c2 = (a2 + b2) / 2
	c3 = (a3 + b3) / 2

	d = Luxor.Point(-10, -10)
	Δ = Luxor.Point(0, -20)

	Luxor.fontsize(20)
	
	Luxor.line(a1, b1, :stroke)
	Luxor.text(L"|1\rangle", a1 + d)
	Luxor.line(a2, b2, :stroke)
	Luxor.text(L"|2\rangle", a2 + d)

	Luxor.line(a3, b3, :stroke)
	Luxor.text(L"|3\rangle", a3 + d)

	Luxor.sethue("orange")
	Luxor.arrow(c1, c2 + Δ)
	Luxor.text(L"\Omega", Luxor.Point(-120, 20))

	Luxor.sethue("mediumvioletred")
	Luxor.arrow(c2, c3)
	Luxor.text(L"\gamma_3", Luxor.Point(80, 0))
end 400 400
```

![lambda](https://user-images.githubusercontent.com/6159838/151342145-126ce8ae-8e2b-4a1b-8e6d-e5a2ea994e78.png)

**Comment by cormullion** [comment]
Hi! 

(I think you always have to install MathTeXEngine separately - this is the way Requires.jl works? But you shouldn't have to install LatexStrings.jl since it's now a dependency of Luxor version 3.0)

There are a few possible things going on here. It might be something to do with the fonts, or it might be something to do with MathTexEngine; it could of course be something to do with Luxor but I don't think much happens in `Luxor.text()` that could displace certain glyphs.

On my system - MacOS - I see this:

<img width="668" alt="Screenshot 2022-01-27 at 11 32 27" src="https://user-images.githubusercontent.com/52289/151350893-b753b44f-d58d-41a5-80d3-4c10f629e1f7.png">

While I don't know how correct this is, it looks a bit more correct than yours, if not completely correct, so first I'd investigate the fonts. You're not seeing Computer Modern at all, so I wouldn't expect to see math glyphs.

I _think_ that the correct fonts have to be installed in two places: firstly, MathTexEngine expects to find the correct fonts in one of its subdirectories. But Luxor/Cairo _also_ expects to find the font in some known system directory. So copy them rather than move them...

If you don't make any progress on this, I'll ask a few more people for help.

**Comment by gdmsl** [comment]
Thanks.

I tried to copy or symlink the fonts used by MathTeXEngine into my `~/.local/share/fonts` directory. Now the fonts used in the picture is different, however the symbol for `\rangle` is not found.

I will continue trying and maybe inspect the SVG output and running out of Pluto

Yes, your version displays the correct symbol but it appears to be displaced. As a reference, `L"|1\rangle"` should look like

![correct](https://user-images.githubusercontent.com/6159838/151359333-c936f21a-aca9-48f0-aba5-35e72ea970ac.png)

**Comment by cormullion** [comment]
@davibarreira If you have a few spare minutes, can you reproduce this?

**Comment by davibarreira** [comment]
Ok. I reproduced it. It looks like a strange bug. I'll check to see if this problem is in MathTeXEngine, or in the Luxor implementation. My guess is that it's in MathTeXEngine, since it's specific to this symbol.

**Comment by davibarreira** [comment]
My guess was correct. Here is the issue: 
https://github.com/Kolaru/MathTeXEngine.jl/issues/46
:cry:

**Comment by gdmsl** [comment]
I did one more trial. It seems to work after symlinking the fonts in the user fonts directory, rebuilding both Luxor and Cairo, and restarting the PC.

**Comment by davibarreira** [comment]
Really? It's now in the correct place? That very strange. But yeah, the issue is not Luxor.

**Comment by davibarreira** [comment]
The proper solution is to solve this in MathTeXEngine. BUUUT, I could implement a little ugly solution here for Luxor.
Although, this would probably not be ideal, right @cormullion ?

**Comment by davibarreira** [comment]
@gdmsl , can you detailed what you did with the symlinking? The issue is for sure not Luxor, cause the same happens in Makie.
I'll try to submit a PR to MathTeXEngine if I'm able to fix it there. But I was wondering why your solution solved the problem.

**Comment by gdmsl** [comment]
Yes I did:

```
$ ln -sf ~/.julia/packages/MathTeXEngine/ZP0gS/assets/fonts/ComputerModern/cmex10.ttf ~/.local/share/fonts/
$ ln -sf ~/.julia/packages/MathTeXEngine/ZP0gS/assets/fonts/NewComputerModern/NewCM* ~/.local/share/fonts/
```
Oddly enough, I am not experiencing at all the problem with Makie. Started using Makie.jl yesterday and all the plots had the right alignment of the `\rangle`, `\langle` and `\dagger` was displaying properly.

And yes, after symlink, build and restart the symbol is not even displaced.

![fixed](https://user-images.githubusercontent.com/6159838/151371210-5aad76c6-1084-44f0-b246-fced38fcd55c.png)

**Comment by cormullion** [comment]
Well, that's the Wonderful Wacky World of Fonts for you... 😄😄

@davibarreira Thanks for the investigation! I think we should do nothing until we know more...

**Comment by GiggleLiu** [comment]
![image](https://user-images.githubusercontent.com/6257240/173517810-dc4ee313-fc02-46a5-b612-6b8d2f88b932.png)

After installing ComputerCMU, the generated latex string is still not rendered properly
```julia
(base) ➜  ~ fc-list | grep Computer
/usr/local/share/fonts/NewCM10-Regular.otf: NewComputerModern,NewComputerModern10:style=10 Regular,Regular
/home/leo/.local/share/fonts/ComputerModern/cmex10.ttf: cmex10:style=Regular
/home/leo/.local/share/fonts/NewComputerModern/NewCMMath-Regular.otf: NewComputerModern Math:style=Regular
/usr/local/share/fonts/NewCM10-Bold.otf: NewComputerModern,NewComputerModern 10:style=10 Bold,Bold
/home/leo/.local/share/fonts/NewCM10-BoldItalic.otf: NewComputerModern,NewComputerModern 10:style=10 Bold Italic,Bold Italic
/usr/local/share/fonts/NewCM10-Italic.otf: NewComputerModern,NewComputerModern 10:style=10 Italic,Italic
/home/leo/.local/share/fonts/NewCMMath-Regular.otf: NewComputerModern Math:style=Regular
/home/leo/.local/share/fonts/NewCMMath-Book.otf: NewComputerModern Math:style=Book
/home/leo/.local/share/fonts/NewCM10-Italic.otf: NewComputerModern,NewComputerModern 10:style=10 Italic,Italic
/home/leo/.local/share/fonts/NewComputerModern/NewCM10-Italic.otf: NewComputerModern,NewComputerModern 10:style=10 Italic,Italic
/home/leo/.local/share/fonts/NewComputerModern/NewCMMath-Book.otf: NewComputerModern Math:style=Book
/home/leo/.local/share/fonts/NewComputerModern/NewCM10-Regular.otf: NewComputerModern,NewComputerModern10:style=10 Regular,Regular
/usr/local/share/fonts/NewCMMath-Book.otf: NewComputerModern Math:style=Book
/usr/local/share/fonts/NewCMMath-Regular.otf: NewComputerModern Math:style=Regular
/home/leo/.local/share/fonts/NewComputerModern/NewCM10-Bold.otf: NewComputerModern,NewComputerModern 10:style=10 Bold,Bold
/usr/local/share/fonts/NewCM10-BoldItalic.otf: NewComputerModern,NewComputerModern 10:style=10 Bold Italic,Bold Italic
/home/leo/.local/share/fonts/NewComputerModern/NewCM10-BoldItalic.otf: NewComputerModern,NewComputerModern 10:style=10 Bold Italic,Bold Italic
/home/leo/.local/share/fonts/NewCM10-Regular.otf: NewComputerModern,NewComputerModern10:style=10 Regular,Regular
/home/leo/.local/share/fonts/NewCM10-Bold.otf: NewComputerModern,NewComputerModern 10:style=10 Bold,Bold
```

System: Ubuntu 22.04, Julia 1.8, Luxor 3.3

**Comment by hyrodium** [comment]
>System: Ubuntu 22.04, Julia 1.8, Luxor 3.3.0

I think the setup script in `.github/workflows/ci.yml` may be helpful.

https://github.com/JuliaGraphics/Luxor.jl/blob/ae22bae62255827b901c2fdcb2b1a11bb4dcd3d1/.github/workflows/ci.yml#L68-L70

The documentation about the font installation can be improved, and I can help with Linux (and perhaps Windows).

**Comment by cormullion** [comment]
it’s a pity MathTexEngine doesn’t use the standard set of LaTeX fonts if they’re present and activated. 🙁

**Comment by GiggleLiu** [comment]
@cormullion Thank you very much, you solved my problem. It turns out I copied the fonts from an older version of MathTexEngine and the font "cmmi10" is missing in that one. 

However, there are still some glitch when rendering an expression like:
![image](https://user-images.githubusercontent.com/6257240/173620337-ba9ce82b-49c4-4cbe-a190-854091b31d02.png)

The logic of `MathTexEngine` a bit wield, when I used dashed lines, the horizontal line in `frac{}{}` also becomes dashed. Does it implements a mixed mode of UTF8 and drawing or it only implements the UTF8 part. Why not converting everything to vector graphs?

**Comment by cormullion** [comment]
Hi! That's a fair question. I think it's OK to call MathTexEngine a work in progress, and I don't know how much of the LaTeX "standard" it can do, given that it's not LaTex at all.

The code that interprets the LaTeX output as Luxor instructions was written by @davibarreira, who will know more about how it actually works than I do, since I know nothing about it ... :) If you supply the string you're using, perhaps it can be analysed ...?
